//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aleman
    {
        public Aleman()
        {
            this.español = new HashSet<español>();
        }
    
        public int codigo { get; set; }
        public string Palabra { get; set; }
    
        public virtual ICollection<español> español { get; set; }
    }
}
