//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    
    public partial class español
    {
        public int codigo { get; set; }
        public string Palabra { get; set; }
        public Nullable<int> codigoingles { get; set; }
        public Nullable<int> codigofrances { get; set; }
        public Nullable<int> codigoaleman { get; set; }
    
        public virtual Aleman Aleman { get; set; }
        public virtual Frances Frances { get; set; }
        public virtual Ingles Ingles { get; set; }
    }
}
